run:
  tests: false
issues:
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - gocyclo
    - gofmt
