language: go

go:
  - "1.12.x"
  - "1.13.x"
  - "tip"

env:
  - GO111MODULE=on

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0

install:
  - go mod download

script:
  - go test ./... -v -coverprofile coverage.txt -covermode count -coverpkg ./...
  - golangci-lint run ./...

after_script:
  - bash <(curl -s https://codecov.io/bash)